server:
  port: 8010
spring:
  application:
    name:  notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"