server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  # Optional
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  # MOVED TO JAVA CONFIG.
  # cloud:
  #   gateway:
  #     server:
  #       webflux:
  #         routes:
  #           - id: room-service
  #             uri: lb://room-service
  #             predicates:
  #               - Path=/api/rooms/**
  #           - id: booking-service
  #             uri: lb://booking-service
  #             predicates:
  #               - Path=/api/bookings/**
  #           # Optional - To access eureka from gateway
  #           - id: eureka-server
  #             uri: http://${EUREKA_HOST:localhost}:8761
  #             predicates:
  #               - Path=/services
  #             filters:
  #               - StripPrefix=1
  #           - id: eureka-static
  #             uri: http://${EUREKA_HOST:localhost}:8761
  #             predicates:
  #               - Path=/eureka/**,/lastn/**