server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

#Only in development (checks for expired leases - 10 sec)
  server:
    eviction-interval-timer-in-ms: 10000