server:
  port: 8005

spring:
  application:
    name: booking-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
  datasource:
    url: jdbc:h2:mem:bookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

rabbitmq:
  exchange:
    name: hotel.exchange
  routing:
    key: booking.created
  queue:
    name: booking.notifications

management:
  endpoints:
    web:
      exposure:
        include:
        - shutdown
        - health
        - beans
  endpoint:
    shutdown:
      access: unrestricted 