server:
  port: 8001

spring:
  application:
    name: room-service
  datasource:
    url: jdbc:h2:mem:roomsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - shutdown
          - health
  endpoint:
    shutdown:
      access: unrestricted
